name: Run Script

description: Run Script, please note this action should be executed from linux/macos builds since it expects CONDA_RUN and BUILD_ENV_FILE to be set
inputs:
  script:
    description: "script to run"
    default: ""
    type: string
  working-directory:
    description: "working directory"
    default: ""
    type: string

runs:
  using: composite
  steps:
    - name: Run script
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        SCRIPT: ${{ inputs.script }}
      if: ${{ inputs.script != '' }}
      run: |
        set -euxo pipefail
        source "${BUILD_ENV_FILE}"
        if [[ ! -f ${SCRIPT} ]]; then
          echo "::error::Specified pre-script file (${SCRIPT}) not found, not going execute it"
          exit 1
        else
          ${CONDA_RUN} bash "${SCRIPT}"
        fi
