name: Trigger nightly builds for domains

on:
  schedule:
    # every night at 4:30AM
    - cron: 30 4 * * *
  workflow_dispatch:
    inputs:
      domain:
        description: "What domain to trigger"
        required: true
        type: choice
        default: all
        options:
          - vision
          - audio
          - text

jobs:
  tag_nightly_vision:
    if:  inputs.domain == 'vision' || inputs.domain == 'all'
    name: Tag nightly vision
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          repository: pytorch/vision
          token: ${{ secrets.GH_PYTORCHBOT_TOKEN }}
      - run: |
          git tag -f nightly-build
          git push origin -f nightly-build
